# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='defaullt', upload_to='router_specifications'),
            preserve_default=False,
        ),
    ]
