# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.FileField(default='', upload_to='router_specifications'),
            preserve_default=False,
        ),
    ]
